e1=int(input("numarul crt="))
e2=int(input("numarul crt="))
e3=int(input("numarul crt="))
p1=int(input("punctaj="))
p2=int(input("punctaj="))
p3=int(input("punctaj="))
print((p1>p2)and(p1>p3))
print((p2>p1)and(p2>p3))
print((p3>p1)and(p3>p2))